import type { GestureWord } from './gestos.types.js';

// Respaldo usado cuando la IA falla, tarda, rechaza el pedido, devuelve
// contenido inválido, o no hay credencial configurada (mismo criterio que
// trivia-fallback-bank.ts). Banco chico porque Trivia ya probó que alcanza
// como respaldo — se amplía si en la práctica una sala lo agota jugando
// muchas partidas seguidas. Mezcla a propósito cosas, verbos, objetos,
// profesiones, animales, lugares y personajes célebres, sin categorizar.
const FALLBACK_BANK: GestureWord[] = [
  'Elefante',
  'Nadar',
  'Bombero',
  'Guitarra',
  'Torre Eiffel',
  'Cocinar',
  'Astronauta',
  'Jirafa',
  'Paraguas',
  'Bailar',
  'Doctor',
  'Pingüino',
  'Bicicleta',
  'Dormir',
  'Payaso',
  'Canguro',
  'Reloj',
  'Manejar',
  'Piloto',
  'Mono',
  'Escalera',
  'Reír',
  'Maestro',
  'Tigre',
  'Sombrero',
  'Llorar',
  'Pintor',
  'Delfín',
  'Tijeras',
  'Saltar',
  'Cantante',
  'Camello',
  'Espejo',
  'Aplaudir',
  'Chef',
  'Cocodrilo',
  'Vela',
  'Correr',
  'Policía',
  'Pulpo',
  'Escoba',
  'Gatear',
  'Superman',
  'Serpiente',
  'Linterna',
  'Estornudar',
  'Mecánico',
  'Águila',
  'Guante',
  'Rezar',
  'Torero',
  'Búho',
  'Balanza',
  'Peinar',
  'Enfermero',
  'Rana',
  'Termómetro',
  'Tejer',
  'Presidente',
  'Oso',
  'Micrófono',
  'Fumar',
  'Cartero',
  'Cebra',
  'Tambor',
  'Pescar',
  'Salvavidas',
  'Murciélago',
  'Cámara',
  'Empujar',
  'Detective',
  'Foca',
  'Brújula',
  'Rezongar',
  'Panadero',
  'Conejo',
  'Lápiz',
  'Estirar',
  'Buzo',
  'Tortuga',
  'Silbato',
  'Coser',
  'Granjero',
  'Loro',
  'Antena',
  'Bostezar',
];

export function getFallbackGestureWords(): readonly GestureWord[] {
  return FALLBACK_BANK;
}
