import type { RawTriviaQuestion, TriviaCategory } from './trivia.types.js';

// Respaldo usado cuando la IA falla, tarda, rechaza el pedido, devuelve
// contenido inválido, o no hay credencial configurada (ver spec.md →
// "Contenido de IA — Trivia"). No busca variedad infinita, solo que el
// juego nunca se caiga.
const FALLBACK_BANK: Record<TriviaCategory, RawTriviaQuestion[]> = {
  general: [
    { pregunta: '¿Cuál es el metal líquido a temperatura ambiente?', correcta: 'Mercurio', incorrectas: ['Hierro', 'Plomo', 'Cobre'] },
    { pregunta: '¿Cuántos lados tiene un hexágono?', correcta: 'Seis', incorrectas: ['Cinco', 'Siete', 'Ocho'] },
    { pregunta: '¿En qué idioma se escribió originalmente "Don Quijote de la Mancha"?', correcta: 'Español', incorrectas: ['Italiano', 'Francés', 'Portugués'] },
    { pregunta: '¿Cuál es el órgano más grande del cuerpo humano?', correcta: 'La piel', incorrectas: ['El hígado', 'El pulmón', 'El intestino'] },
    { pregunta: '¿Cuántas cuerdas tiene una guitarra clásica?', correcta: 'Seis', incorrectas: ['Cuatro', 'Cinco', 'Siete'] },
    { pregunta: '¿Qué instrumento se usa para medir la temperatura?', correcta: 'El termómetro', incorrectas: ['El barómetro', 'El altímetro', 'El sismógrafo'] },
    { pregunta: '¿Cuál es el fruto del olivo?', correcta: 'La aceituna', incorrectas: ['La almendra', 'La avellana', 'El dátil'] },
    { pregunta: '¿Cómo se llama el estudio del origen de las palabras?', correcta: 'Etimología', incorrectas: ['Semántica', 'Fonética', 'Sintaxis'] },
    { pregunta: '¿Cuál es la moneda oficial de Japón?', correcta: 'El yen', incorrectas: ['El won', 'El yuan', 'El ringgit'] },
    { pregunta: '¿Cuántos meses del año tienen 31 días?', correcta: 'Siete', incorrectas: ['Cinco', 'Seis', 'Ocho'] },
    { pregunta: '¿Qué gas necesitan las plantas para hacer la fotosíntesis?', correcta: 'Dióxido de carbono', incorrectas: ['Oxígeno', 'Nitrógeno', 'Hidrógeno'] },
    { pregunta: '¿Cuál es el hueso más largo del cuerpo humano?', correcta: 'El fémur', incorrectas: ['El húmero', 'La tibia', 'El radio'] },
    { pregunta: '¿Cómo se llama el conjunto de abejas que vive junto?', correcta: 'Enjambre', incorrectas: ['Manada', 'Bandada', 'Rebaño'] },
    { pregunta: '¿Qué color resulta de mezclar azul y amarillo?', correcta: 'Verde', incorrectas: ['Morado', 'Naranja', 'Gris'] },
    { pregunta: '¿Cuántas patas tiene una araña?', correcta: 'Ocho', incorrectas: ['Seis', 'Diez', 'Doce'] },
    { pregunta: '¿Cómo se llama el líder máximo de la Iglesia Católica?', correcta: 'El Papa', incorrectas: ['El patriarca', 'El obispo', 'El cardenal'] },
    { pregunta: '¿Cuál es el metal más abundante en la corteza terrestre?', correcta: 'Aluminio', incorrectas: ['Hierro', 'Cobre', 'Oro'] },
    { pregunta: '¿Qué significa la sigla "ONU"?', correcta: 'Organización de las Naciones Unidas', incorrectas: ['Organización Nacional Unificada', 'Organismo de Naciones Unificadas', 'Oficina de Negociación Universal'] },
    { pregunta: '¿En qué ciudad española se originó la paella?', correcta: 'Valencia', incorrectas: ['Madrid', 'Barcelona', 'Sevilla'] },
    { pregunta: '¿Cuántos colores tiene el arcoíris tradicionalmente?', correcta: 'Siete', incorrectas: ['Cinco', 'Seis', 'Ocho'] },
  ],
  historia: [
    { pregunta: '¿En qué año llegó Cristóbal Colón a América?', correcta: '1492', incorrectas: ['1490', '1500', '1512'] },
    { pregunta: '¿Qué muro cayó en 1989 y marcó el fin de la Guerra Fría?', correcta: 'El Muro de Berlín', incorrectas: ['El Muro de Adriano', 'La Gran Muralla China', 'El Muro de las Lamentaciones'] },
    { pregunta: '¿Quién fue el primer presidente de los Estados Unidos?', correcta: 'George Washington', incorrectas: ['Thomas Jefferson', 'Abraham Lincoln', 'John Adams'] },
    { pregunta: '¿En qué año terminó la Segunda Guerra Mundial?', correcta: '1945', incorrectas: ['1939', '1943', '1950'] },
    { pregunta: '¿Qué civilización construyó Machu Picchu?', correcta: 'Los incas', incorrectas: ['Los aztecas', 'Los mayas', 'Los olmecas'] },
    { pregunta: '¿Qué imperio construyó el Coliseo de Roma?', correcta: 'El Imperio Romano', incorrectas: ['El Imperio Griego', 'El Imperio Bizantino', 'El Imperio Persa'] },
    { pregunta: '¿Quién pintó los frescos del techo de la Capilla Sixtina?', correcta: 'Miguel Ángel', incorrectas: ['Leonardo da Vinci', 'Rafael', 'Donatello'] },
    { pregunta: '¿Qué faraón egipcio es famoso por su máscara funeraria de oro, hallada en 1922?', correcta: 'Tutankamón', incorrectas: ['Ramsés II', 'Keops', 'Akenatón'] },
    { pregunta: '¿Qué barco británico se hundió en 1912 tras chocar con un iceberg?', correcta: 'El Titanic', incorrectas: ['El Lusitania', 'El Britannic', 'El Queen Mary'] },
    { pregunta: '¿Quién lideró la independencia de la India mediante la resistencia pacífica?', correcta: 'Mahatma Gandhi', incorrectas: ['Jawaharlal Nehru', 'Ho Chi Minh', 'Nelson Mandela'] },
    { pregunta: '¿En qué país comenzó el Renacimiento?', correcta: 'Italia', incorrectas: ['Francia', 'España', 'Inglaterra'] },
    { pregunta: '¿Qué antigua civilización construyó las pirámides de Guiza?', correcta: 'Los egipcios', incorrectas: ['Los mayas', 'Los sumerios', 'Los fenicios'] },
    { pregunta: '¿Quién fue el primer hombre en pisar la Luna?', correcta: 'Neil Armstrong', incorrectas: ['Buzz Aldrin', 'Yuri Gagarin', 'John Glenn'] },
    { pregunta: '¿En qué año comenzó la Primera Guerra Mundial?', correcta: '1914', incorrectas: ['1905', '1918', '1920'] },
    { pregunta: '¿Qué emperador francés fue derrotado en la batalla de Waterloo?', correcta: 'Napoleón Bonaparte', incorrectas: ['Luis XVI', 'Carlomagno', 'Luis XIV'] },
    { pregunta: '¿Qué explorador portugués lideró la primera expedición en circunnavegar el globo?', correcta: 'Fernando de Magallanes', incorrectas: ['Vasco da Gama', 'Cristóbal Colón', 'Américo Vespucio'] },
    { pregunta: '¿En qué ciudad se firmó la Declaración de Independencia de Estados Unidos?', correcta: 'Filadelfia', incorrectas: ['Nueva York', 'Boston', 'Washington D.C.'] },
    { pregunta: '¿Qué antiguo pueblo inventó la escritura cuneiforme?', correcta: 'Los sumerios', incorrectas: ['Los egipcios', 'Los fenicios', 'Los babilonios'] },
    { pregunta: '¿Qué revolución comenzó en Francia en 1789?', correcta: 'La Revolución Francesa', incorrectas: ['La Revolución Industrial', 'La Revolución Rusa', 'La Revolución Americana'] },
    { pregunta: '¿En qué año cayó el Imperio Romano de Occidente?', correcta: '476 d.C.', incorrectas: ['313 d.C.', '800 d.C.', '1000 d.C.'] },
  ],
  geografia: [
    { pregunta: '¿Cuál es el río más largo de Sudamérica?', correcta: 'El Amazonas', incorrectas: ['El Orinoco', 'El Paraná', 'El Magdalena'] },
    { pregunta: '¿Cuál es el desierto cálido más grande del mundo?', correcta: 'El Sahara', incorrectas: ['El Gobi', 'El Atacama', 'El Kalahari'] },
    { pregunta: '¿Cuál es el océano más grande del mundo?', correcta: 'El Pacífico', incorrectas: ['El Atlántico', 'El Índico', 'El Ártico'] },
    { pregunta: '¿Cuál es la montaña más alta del mundo?', correcta: 'El Everest', incorrectas: ['El Aconcagua', 'El Kilimanjaro', 'El K2'] },
    { pregunta: '¿Qué país europeo tiene forma de bota en el mapa?', correcta: 'Italia', incorrectas: ['España', 'Grecia', 'Portugal'] },
    { pregunta: '¿Cuál es el país más grande del mundo por superficie?', correcta: 'Rusia', incorrectas: ['Canadá', 'China', 'Estados Unidos'] },
    { pregunta: '¿En qué continente está Egipto?', correcta: 'África', incorrectas: ['Asia', 'Europa', 'Oceanía'] },
    { pregunta: '¿Cuál es la capital de Australia?', correcta: 'Canberra', incorrectas: ['Sídney', 'Melbourne', 'Perth'] },
    { pregunta: '¿Cuál es el lago con más volumen de agua dulce del mundo?', correcta: 'El lago Baikal', incorrectas: ['El lago Victoria', 'El lago Superior', 'El lago Titicaca'] },
    { pregunta: '¿Qué cordillera recorre gran parte de Sudamérica de norte a sur?', correcta: 'Los Andes', incorrectas: ['Los Alpes', 'El Himalaya', 'Las Rocosas'] },
    { pregunta: '¿Cuál es la capital de Canadá?', correcta: 'Ottawa', incorrectas: ['Toronto', 'Vancouver', 'Montreal'] },
    { pregunta: '¿Qué estrecho separa España de África?', correcta: 'El estrecho de Gibraltar', incorrectas: ['El estrecho de Magallanes', 'El estrecho de Bering', 'El Bósforo'] },
    { pregunta: '¿A qué país se lo conoce como "la tierra del sol naciente"?', correcta: 'Japón', incorrectas: ['China', 'Corea del Sur', 'Tailandia'] },
    { pregunta: '¿En qué países se encuentran las cataratas del Iguazú?', correcta: 'Argentina y Brasil', incorrectas: ['Perú y Colombia', 'Venezuela y Guyana', 'Chile y Bolivia'] },
    { pregunta: '¿Cuál es el punto más bajo de la superficie terrestre en tierra firme?', correcta: 'El Mar Muerto', incorrectas: ['El Valle de la Muerte', 'La fosa de las Marianas', 'El lago Asal'] },
    { pregunta: '¿En qué país está la Torre Eiffel?', correcta: 'Francia', incorrectas: ['Bélgica', 'Alemania', 'Reino Unido'] },
    { pregunta: '¿Cuál es el país más pequeño del mundo?', correcta: 'El Vaticano', incorrectas: ['Mónaco', 'San Marino', 'Liechtenstein'] },
    { pregunta: '¿Qué línea imaginaria divide la Tierra en hemisferio norte y sur?', correcta: 'El ecuador', incorrectas: ['El meridiano de Greenwich', 'El trópico de Cáncer', 'El círculo polar ártico'] },
    { pregunta: '¿Cuál es la capital de Egipto?', correcta: 'El Cairo', incorrectas: ['Alejandría', 'Luxor', 'Giza'] },
    { pregunta: '¿Cuál es la capital de Perú?', correcta: 'Lima', incorrectas: ['Cusco', 'Arequipa', 'Trujillo'] },
  ],
  ciencia: [
    { pregunta: '¿Cuál es el planeta más cercano al Sol?', correcta: 'Mercurio', incorrectas: ['Venus', 'La Tierra', 'Marte'] },
    { pregunta: '¿Cuál es el símbolo químico del oro?', correcta: 'Au', incorrectas: ['Ag', 'Fe', 'Or'] },
    { pregunta: '¿Cuántos huesos tiene el cuerpo humano adulto?', correcta: '206', incorrectas: ['186', '226', '246'] },
    { pregunta: '¿Qué gas es el más abundante en la atmósfera terrestre?', correcta: 'El nitrógeno', incorrectas: ['El oxígeno', 'El dióxido de carbono', 'El hidrógeno'] },
    { pregunta: '¿Quién formuló la teoría de la relatividad?', correcta: 'Albert Einstein', incorrectas: ['Isaac Newton', 'Galileo Galilei', 'Stephen Hawking'] },
    { pregunta: '¿Cuál es, aproximadamente, la velocidad de la luz en el vacío?', correcta: '300.000 km/s', incorrectas: ['150.000 km/s', '1.000.000 km/s', '30.000 km/s'] },
    { pregunta: '¿Qué parte de la célula contiene el material genético?', correcta: 'El núcleo', incorrectas: ['La mitocondria', 'El citoplasma', 'La membrana'] },
    { pregunta: '¿Cuál es el elemento químico más ligero?', correcta: 'El hidrógeno', incorrectas: ['El helio', 'El litio', 'El oxígeno'] },
    { pregunta: '¿Cuántos planetas tiene el sistema solar?', correcta: 'Ocho', incorrectas: ['Siete', 'Nueve', 'Diez'] },
    { pregunta: '¿Qué científico propuso la teoría de la evolución por selección natural?', correcta: 'Charles Darwin', incorrectas: ['Gregor Mendel', 'Louis Pasteur', 'Alfred Wallace'] },
    { pregunta: '¿Qué órgano se encarga de bombear la sangre?', correcta: 'El corazón', incorrectas: ['El hígado', 'El riñón', 'El pulmón'] },
    { pregunta: '¿Qué unidad se usa para medir la fuerza?', correcta: 'El newton', incorrectas: ['El vatio', 'El joule', 'El pascal'] },
    { pregunta: '¿Cómo se llama el proceso por el cual las plantas producen su alimento?', correcta: 'La fotosíntesis', incorrectas: ['La respiración', 'La fermentación', 'La transpiración'] },
    { pregunta: '¿Cuál es el hueso más pequeño del cuerpo humano?', correcta: 'El estribo', incorrectas: ['La falange', 'La rótula', 'La clavícula'] },
    { pregunta: '¿Qué tipo de animal es una ballena?', correcta: 'Un mamífero', incorrectas: ['Un pez', 'Un reptil', 'Un anfibio'] },
    { pregunta: '¿Qué metal se usa comúnmente para conducir electricidad en los cables?', correcta: 'El cobre', incorrectas: ['El plomo', 'El estaño', 'El zinc'] },
    { pregunta: '¿Cuántos pares de cromosomas tiene el ser humano?', correcta: '23', incorrectas: ['21', '25', '46'] },
    { pregunta: '¿Qué instrumento se usa para observar objetos muy pequeños?', correcta: 'El microscopio', incorrectas: ['El telescopio', 'El periscopio', 'El estetoscopio'] },
    { pregunta: '¿Qué vitamina produce la piel gracias a la luz solar?', correcta: 'La vitamina D', incorrectas: ['La vitamina C', 'La vitamina A', 'La vitamina B12'] },
    { pregunta: '¿Qué le pasa al agua a 0°C a presión normal?', correcta: 'Se congela', incorrectas: ['Hierve', 'Se evapora', 'Se mantiene líquida siempre'] },
  ],
  deportes: [
    { pregunta: '¿Cada cuántos años se celebran los Juegos Olímpicos de verano?', correcta: 'Cada 4 años', incorrectas: ['Cada 2 años', 'Cada 3 años', 'Cada 5 años'] },
    { pregunta: '¿Cuántos jugadores tiene un equipo de fútbol en la cancha, sin contar suplentes?', correcta: 'Once', incorrectas: ['Diez', 'Doce', 'Nueve'] },
    { pregunta: '¿En qué juego se usa el término "jaque mate"?', correcta: 'Ajedrez', incorrectas: ['Dominó', 'Backgammon', 'Damas'] },
    { pregunta: '¿Cuántos puntos vale un touchdown en fútbol americano?', correcta: 'Seis', incorrectas: ['Tres', 'Cinco', 'Siete'] },
    { pregunta: '¿En qué país se originó el sumo?', correcta: 'Japón', incorrectas: ['China', 'Corea del Sur', 'Mongolia'] },
    { pregunta: '¿A cuántos sets se juega como máximo un partido de tenis de Grand Slam masculino?', correcta: 'Cinco', incorrectas: ['Tres', 'Siete', 'Cuatro'] },
    { pregunta: '¿Qué país ganó la Copa Mundial de fútbol de 2018?', correcta: 'Francia', incorrectas: ['Croacia', 'Brasil', 'Alemania'] },
    { pregunta: '¿Cuántos jugadores tiene un equipo de baloncesto en la cancha?', correcta: 'Cinco', incorrectas: ['Seis', 'Siete', 'Cuatro'] },
    { pregunta: '¿En qué deporte se compite por la "Copa Davis"?', correcta: 'Tenis', incorrectas: ['Golf', 'Fútbol', 'Rugby'] },
    { pregunta: '¿Cuántos hoyos tiene un campo de golf reglamentario?', correcta: '18', incorrectas: ['16', '20', '9'] },
    { pregunta: '¿Qué nadador estadounidense ganó 23 medallas de oro olímpicas?', correcta: 'Michael Phelps', incorrectas: ['Mark Spitz', 'Ryan Lochte', 'Ian Thorpe'] },
    { pregunta: '¿En qué ciudad se disputó el primer Mundial de fútbol en 1930?', correcta: 'Montevideo', incorrectas: ['Buenos Aires', 'Río de Janeiro', 'Ciudad de México'] },
    { pregunta: '¿Cuántos años dura un ciclo olímpico?', correcta: 'Cuatro', incorrectas: ['Dos', 'Tres', 'Cinco'] },
    { pregunta: '¿Cómo se llama el deporte ecuestre donde el jinete salta obstáculos?', correcta: 'Salto ecuestre', incorrectas: ['Polo', 'Rodeo', 'Doma clásica'] },
    { pregunta: '¿En qué deporte de raqueta el volante se llama "birdie"?', correcta: 'Bádminton', incorrectas: ['Tenis de mesa', 'Squash', 'Voleibol'] },
    { pregunta: '¿Cuántos jugadores hay en un equipo de voleibol en la cancha?', correcta: 'Seis', incorrectas: ['Cinco', 'Siete', 'Cuatro'] },
    { pregunta: '¿Qué país ha ganado más veces la Copa Mundial de fútbol masculina?', correcta: 'Brasil', incorrectas: ['Alemania', 'Italia', 'Argentina'] },
    { pregunta: '¿En qué torneo de tenis se juega sobre césped en Londres cada año?', correcta: 'Wimbledon', incorrectas: ['Roland Garros', 'El US Open', 'El Abierto de Australia'] },
    { pregunta: '¿Cuántos asaltos tiene oficialmente una pelea de boxeo profesional de campeonato?', correcta: 'Doce', incorrectas: ['Diez', 'Ocho', 'Quince'] },
    { pregunta: '¿Qué representa la camiseta amarilla en el Tour de Francia?', correcta: 'Al líder de la clasificación general', incorrectas: ['Al mejor sprinter', 'Al mejor escalador', 'Al ciclista más joven'] },
  ],
  entretenimiento: [
    { pregunta: '¿Quién dirigió la trilogía original de "El Padrino"?', correcta: 'Francis Ford Coppola', incorrectas: ['Martin Scorsese', 'Steven Spielberg', 'George Lucas'] },
    { pregunta: '¿Qué banda británica lanzó el álbum "Abbey Road"?', correcta: 'The Beatles', incorrectas: ['The Rolling Stones', 'Pink Floyd', 'Queen'] },
    { pregunta: '¿Quién interpretó a Jack en la película "Titanic" (1997)?', correcta: 'Leonardo DiCaprio', incorrectas: ['Brad Pitt', 'Matt Damon', 'Tom Cruise'] },
    { pregunta: '¿Qué estudio de animación creó "Toy Story"?', correcta: 'Pixar', incorrectas: ['DreamWorks', 'Illumination', 'Studio Ghibli'] },
    { pregunta: '¿Cuál es el nombre real del personaje "Iron Man"?', correcta: 'Tony Stark', incorrectas: ['Steve Rogers', 'Bruce Banner', 'Peter Parker'] },
    { pregunta: '¿Qué actor interpretó a Jack Sparrow en "Piratas del Caribe"?', correcta: 'Johnny Depp', incorrectas: ['Orlando Bloom', 'Geoffrey Rush', 'Javier Bardem'] },
    { pregunta: '¿Quién escribió la saga de libros de "Harry Potter"?', correcta: 'J.K. Rowling', incorrectas: ['J.R.R. Tolkien', 'C.S. Lewis', 'Suzanne Collins'] },
    { pregunta: '¿Cómo se llama la serie de televisión que sigue a la familia Stark en Poniente?', correcta: 'Juego de Tronos', incorrectas: ['Vikingos', 'The Crown', 'Los Bridgerton'] },
    { pregunta: '¿Cómo se llama el famoso ratón que es la mascota de Disney?', correcta: 'Mickey Mouse', incorrectas: ['Bugs Bunny', 'Tom', 'Jerry'] },
    { pregunta: '¿Quién compuso "Las Cuatro Estaciones"?', correcta: 'Antonio Vivaldi', incorrectas: ['Johann Sebastian Bach', 'Wolfgang Amadeus Mozart', 'Ludwig van Beethoven'] },
    { pregunta: '¿Qué cantante es conocida como "la Reina del Pop"?', correcta: 'Madonna', incorrectas: ['Britney Spears', 'Beyoncé', 'Lady Gaga'] },
    { pregunta: '¿En qué ciudad ficticia vive Batman?', correcta: 'Gotham City', incorrectas: ['Metrópolis', 'Central City', 'Star City'] },
    { pregunta: '¿Qué película de Disney cuenta la historia de un león llamado Simba?', correcta: 'El Rey León', incorrectas: ['Madagascar', 'Zootopia', 'Tarzán'] },
    { pregunta: '¿Qué actor interpretó al Joker en "The Dark Knight" (2008)?', correcta: 'Heath Ledger', incorrectas: ['Jack Nicholson', 'Joaquin Phoenix', 'Jared Leto'] },
    { pregunta: '¿Cómo se llama el mago protagonista creado por J.K. Rowling?', correcta: 'Harry Potter', incorrectas: ['Percy Jackson', 'Frodo Bolsón', 'Aragorn'] },
    { pregunta: '¿Qué banda de rock formaron John Lennon y Paul McCartney?', correcta: 'The Beatles', incorrectas: ['Led Zeppelin', 'The Who', 'Oasis'] },
    { pregunta: '¿Qué famoso detective británico creó Arthur Conan Doyle?', correcta: 'Sherlock Holmes', incorrectas: ['Hercule Poirot', 'Philip Marlowe', 'Dick Tracy'] },
    { pregunta: '¿Qué serie animada tiene como protagonistas a Homero y Bart Simpson?', correcta: 'Los Simpson', incorrectas: ['Padre de familia', 'South Park', "Bob's Burgers"] },
    { pregunta: '¿Qué actriz interpretó a Hermione Granger en las películas de Harry Potter?', correcta: 'Emma Watson', incorrectas: ['Emma Stone', 'Emma Roberts', 'Bonnie Wright'] },
    { pregunta: '¿Qué compositor alemán quedó sordo y aun así compuso su Novena Sinfonía?', correcta: 'Ludwig van Beethoven', incorrectas: ['Johann Sebastian Bach', 'Franz Schubert', 'Johannes Brahms'] },
  ],
};

export function getFallbackQuestions(categoria: TriviaCategory): readonly RawTriviaQuestion[] {
  return FALLBACK_BANK[categoria];
}
